# This docker compose file is solely used for running the integration tests
version: "3.9"  # optional since v1.27.0
services:
  lucidmq-server:
    image: lucidmq:latest
    build: 
      context: .
      dockerfile: images/Lucidmq.Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "6969:6969"
    networks:
      - testing-network
  test-runner:
    image: lucidmq-test
    build: 
      context: .
      dockerfile: images/GoIntegration.Dockerfile
    environment:
      - LUCIDMQ_SERVER_HOST=lucidmq-server
      - LUCIDMQ_SERVER_PORT=6969
    depends_on:
      - lucidmq-server
    networks:
      - testing-network
networks:
  testing-network:
    driver: bridge