name: lucidmq-ci

on:
  push:
    branches:
      - '*'
    paths:
      - "lucidmq/**"
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - "lucidmq/**"

jobs:
  build_and_test:
    name: LucidMQ - Build and Test
    runs-on: ubuntu-latest
    container:
      image: registry.nocaply.com/lucidmq-base:latest
      options: "--user root --entrypoint /bin/bash"
      credentials:
        username: ${{  secrets.DOCKER_REGISTRY_USER }}
        password: ${{  secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: investigate
        run: |
          echo $PATH
          cargo --help
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run with Docker
        run: |
          cd lucidmq
          cargo build --verbose
