name: lucidmq-cli-ci

on:
  push:
    branches:
      - '*'
    paths:
      - "lucidmq-cli/**"
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - "lucidmq/**"

jobs:
  build_and_test:
    name: LucidMQ-CLI - Build and Test
    runs-on: ubuntu-latest
    container:
      image: registry.nocaply.com/lucidmq-base:latest
      options: --user root
      credentials:
        username: ${{  secrets.DOCKER_REGISTRY_USER }}
        password: ${{  secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd lucidmq
      - run: cargo build --verbose
      - run: cargo test --verbose