name: lucidmq-ci

on:
  push:
    branches:
      - '*'
    paths:
      - "lucidmq/**"
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - "lucidmq/**"

jobs:
  build_and_test:
    name: LucidMQ - Build and Test
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./lucidmq
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose