name: lucidmq-ci

on:
  push:
    branches:
      - '*'
    paths:
      - "lucidmq/**"
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - "lucidmq/**"

jobs:
  build_and_test:
    name: LucidMQ - Build and Unit Test
    runs-on: ubuntu-latest
    container:
      image: registry.nocaply.com/lucidmq-base:latest
      options: "--user root --entrypoint /bin/bash"
      credentials:
        username: ${{  secrets.DOCKER_REGISTRY_USER }}
        password: ${{  secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd lucidmq
      - name: LucidMQ Build
        run: cargo build --verbose
      - name: LucidMQ Test
        run: cargo test --verbose
  integration_tests:
    name: LucidMQ - Integration Tests
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Registry Login
        run: 'echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin'
        shell: bash
        env: 
          DOCKER_USER: ${{  secrets.DOCKER_REGISTRY_USER }}
          DOCKER_PASS: ${{  secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Docker Compose Build and Run
        run: docker-compose up --build --exit-code-from test-runner