name: lucidmq-ci

on:
  push:
    branches:
      - 'master'
    paths:
      - "lucidmq/**"
  workflow_dispatch:
    branches:
      - 'master'
    paths:
      - "lucidmq/**"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./lucidmq
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}