name: lucidmq-cli-ci

on:
  push:
    branches:
      - '*'
    paths:
      - "lucidmq-cli/**"
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - "lucidmq/**"

jobs:
  build_and_test:
    name: LucidMQ-CLI - Build and Test
    runs-on: ubuntu-latest
    container:
      image: registry.nocaply.com/lucidmq-base:latest
      options: "--user root --entrypoint /bin/bash"
      credentials:
        username: ${{  secrets.DOCKER_REGISTRY_USER }}
        password: ${{  secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: LucidMQ CLI Build
        run: cargo build --manifest-path=lucidmq-cli/Cargo.toml --verbose
      - name: LucidMQ CLI Test
        run: cargo test --manifest-path=lucidmq-cli/Cargo.toml --verbose