name: nolan-ci

on:
  push:
    branches:
      - '*'
    paths:
      - "nolan/**"
  workflow_dispatch:
    branches:
      - '*'
    paths:
      - "nolan/**"

jobs:
  build_and_test:
    name: Nolan - Build and Test
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./nolan
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          # Disable nightly, since I dont think it's that valuble to test on there
          # - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose